name: Build and Publish NPM

on:
  push:
    tags:
      - 'v*'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
    - name: Check version match
      run: |
        TAG_VERSION=${GITHUB_REF/refs\/tags\/v/}
        PACKAGE_VERSION=$(node -p "require('./package.json').version")
        if [ "$TAG_VERSION" != "$PACKAGE_VERSION" ]; then
          echo "Tag version ($TAG_VERSION) does not match package.json version ($PACKAGE_VERSION)"
          exit 1
        fi
  build-and-publish:
    runs-on: ubuntu-latest
    needs: checks
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Install dependencies (CI command on npm)
        uses: borales/actions-yarn@v5
        with:
          cmd: install --frozen-lockfile
      - name: Build project
        uses: borales/actions-yarn@v5
        with:
          cmd: build
      - name: Publish to npm
        id: npm_publish
        uses: JS-DevTools/npm-publish@v3
        with:
          access: "public"
          token: ${{ secrets.NPM_TOKEN }}
      - if: steps.npm_publish.outputs.type
        run: |
          echo "Version changed: ${{ steps.npm_publish.outputs.old-version }} => ${{ steps.npm_publish.outputs.version }}"
        shell: bash
